### ISSUE TITLE
Disconnect on MongoDB backup!

### ISSUE THREAD

**Issue by mjmasn** [christkv/mongodb-core#139] opened 2016-09-17 17:09 UTC
We're running MeteorJS using a Compose MongoDB database (2.6.9). Since updating to Meteor 1.4.1.1 (which has v2.2.9 of the mongodb npm package, which I think uses 2.0.10 of mongodb-core?) we get an error thrown (MongoDB timeout) whenever a backup runs. This shouldn't happen because the backup member is a separate hidden member and cannot be connected to.

Meteor reconnects ok straight after but it's breaking another package we're using for cron-style jobs and forces us to restart the apps every day at time X when the backup runs.

Probably a tricky one to diagnose but are there any recent changes that could potentially cause this weird behaviour? I have confirmed that the old version of Meteor doesn't have the issue and it could of course be a Meteor bug but a driver issue seems more likely given the error: `MongoError: connection X to x.y.z.mongolayer.com:XXXX timed out`

**Comment by christkv** [comment] 2016-09-19 07:12
it's likely this is a variation of an issue fixed for the 2.2.10 driver.

NODE-818 Replicaset timeouts in initial connect sequence can "no primary found".

https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md

If it's not then the timeout is just caused by failure to connect to the hidden member, and meteor is wrongly re throwing it as an error for some reason.

**Comment by andrewaustin** [comment] 2016-09-23 19:49
I'm running the 2.2.10 driver with mongoose 4.6.1 and see the following:

```
{ [MongoError: connection 7 to 127.0.0.1:32771 timed out]
  name: 'MongoError',
  message: 'connection 7 to 127.0.0.1:32771 timed out' }
```

I have a connection pool of 20. My configuration is:

```
		server:
			poolSize: 20
			socketOptions:
				keepAlive: 1
			ssl: true
			sslValidate: false
```

This seems to have started happening between 2.1.18 and 2.2.10 of node-mongodb-native (based on the versions in Mongoose...I don't see this issue with Mongoose 4.5.10 which used version 2.1.18).

The connection error for me is very intermittent... about 1 in 5 test runs of my service.

Full stack trace:

```
error: [MONGOOSE] connection error loggerName=global, timestamp=2016-09-20T19:11:58.086Z, logLevel=error, stack=Error: connection timeout
at [object Object].<anonymous> (/var/build/workspace/build-realtime/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:168:17)
at emitTwo (events.js:87:13)
at [object Object].emit (events.js:172:7)
at [object Object].listener (/var/build/workspace/build-realtime/node_modules/mongoose/node_modules/mongodb/lib/db.js:1791:14)
at emitOne (events.js:77:13)
at [object Object].emit (events.js:169:7)
at [object Object].<anonymous> (/var/build/workspace/build-realtime/node_modules/mongoose/node_modules/mongodb/lib/server.js:270:14)
at [object Object].g (events.js:260:16)
at emitOne (events.js:77:13)
at [object Object].emit (events.js:169:7)
at [object Object].<anonymous> (/var/build/workspace/build-realtime/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:322:12)
at emitOne (events.js:77:13)
at [object Object].emit (events.js:169:7)
at [object Object].<anonymous> (/var/build/workspace/build-realtime/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:260:12)
at [object Object].g (events.js:260:16)
at emitTwo (events.js:87:13)
at [object Object].emit (events.js:172:7)
at TLSSocket.<anonymous> (/var/build/workspace/build-realtime/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:172:10)
at TLSSocket.g (events.js:260:16)
at emitNone (events.js:67:13)
at TLSSocket.emit (events.js:166:7)
at TLSSocket.Socket._onTimeout (net.js:332:8)
at _runOnTimeout (timers.js:524:11)
at _makeTimerTimeout (timers.js:515:3)
at Timer.unrefTimeout (timers.js:584:5)
```

**Comment by christkv** [comment] 2016-09-23 20:23
I would suggest opening that in the mongoose project with reproducible steps so they can diagnose it and then open a ticket with this project.

**Comment by andrewaustin** [comment] 2016-09-23 20:27
It's just re-emitting the underlying error from mongodb-core: https://github.com/Automattic/mongoose/blob/master/lib/drivers/node-mongodb-native/connection.js#L167

**Comment by christkv** [comment] 2016-09-23 20:29
If these are test cases are you making sure you are disconnecting when you are done using a connection implicit. If you have a test that's not doing that then you could see this intermittently depending if your tests take more or less time to run causing the timeout to be triggered.

**Comment by mjmasn** [comment] 2016-09-24 11:04
The original problem was at least partially fixed by upgrading our compose deployment to MongoDB 3.0.11. We've only had one timeout in the last 4 days, and our production machines recovered this time (Meteor caught the error, which possibly makes sense - am I right in saying the error format changed slightly with Mongo 3.0? e.g. err->errmsg in error objects). 

My local machine connected to the same MongoDB deployment did still fail with the uncaught Mongo error despite running identical code. Bit of a weird one...

**Comment by christkv** [comment] 2016-09-25 07:10
@mjmasn it's possible. 3.0 did a big cleanup on the error messages returned from the server so it's possible 2.6 had some messages that changed the field name.

**Comment by christkv** [comment] 2016-10-20 20:23
closing as no new information

**Closed by christkv** 2016-10-20 20:23 UTC
