### ISSUE TITLE
When a replica set doesn't have an active primary, commands aren't buffered and return a type error

### ISSUE THREAD

**Issue by gfzabarino** [christkv/mongodb-core#167] opened 2017-03-06 16:33 UTC
This is using mongoose@4.8.6, mongodb@2.2.24 and mongodb-core@2.1.8.

@christkv I ran again tests made in https://jira.mongodb.org/browse/NODE-893, and when a command is executed against a replica set that is electing a new primary, a type error is caught and returned:

```
TypeError: Cannot read property 'command' of undefined
    at nextFunction (xxx/node_modules/mongodb-core/lib/cursor.js:568:51)
```

The issue is that `self.server = self.topology.getServer(self.options);` sets an error to `self.server`, that being `no primary server available`. Then, when trying to call `self.query = self.server.wireProtocolHandler.command(...` the error is caught and returned.

I don't know with extent how the driver works, but above that there are statements that seem to buffer commands if there isn't a connection in place:

```
    // Topology is not connected, save the call in the provided store to be
    // Executed at some point when the handler deems it's reconnected
    if(!self.topology.isConnected(self.options) && self.disconnectHandler != null) {
      if (self.topology.isDestroyed()) {
        // Topology was destroyed, so don't try to wait for it to reconnect
        return callback(new MongoError('Topology was destroyed'));
      }
      return self.disconnectHandler.addObjectAndMethod('cursor', self, 'next', [callback], callback);
    }
```

I debugged, and `self.topology.isConnected` returns true when there's no primary available. I'm not sure if that's correct or not, but it is the cause of the current command being executed to fail with an error.

**Comment by gfzabarino** [comment] 2017-03-06 16:39
Hmm it seems the cause of why `isConnected` is returning true is because `secondaryOnlyConnectionAllowed` is `true` and there are connected secondaries. However, I don't see why that setting is `true`. I'll continue digging.

**Comment by gfzabarino** [comment] 2017-03-06 16:52
Lame, I've set `connectWithNoPrimary` in my connection options which is then translated to `secondaryOnlyConnectionAllowed `.

When `connectWithNoPrimary` / `secondaryOnlyConnectionAllowed ` is true, and there's no `readPreference` set, that's set by default to primary, and then the error is returned. Maybe that's an issue?

**Comment by christkv** [comment] 2017-03-06 16:55
what options and uri string are you using ?

**Comment by christkv** [comment] 2017-03-06 16:55
what you are seeing usually means bufferMaxEntries is set to 0 or a low value.

**Comment by christkv** [comment] 2017-03-06 16:56
secondaryOnlyConnectionAllowed should also never be on by default

**Comment by gfzabarino** [comment] 2017-03-06 16:57
Yup, I think I left it by mistake when trying from that old issue I had with replica set re-connection. I removed it from the options, and buffering worked good (it waited for the primary to be elected, and then returned successfully).

**Comment by gfzabarino** [comment] 2017-03-06 17:00
Connection uri string: `mongodb://localhost:12345,localhost:27018,localhost:27019/dbname?replicaSet=rs0`

options:

```
  var socketOptions = {
    keepAlive: 120000,
    connectTimeoutMS: 3000,
    socketTimeoutMS: 10000
  };
  var options = {
    server: {
      socketOptions: socketOptions
    },
    replset: {
      haInterval: 5000,
      connectWithNoPrimary: true,
      socketOptions: socketOptions
    },
    safe: { j: 'majority' }
  };
  mongoose.connect(config.db, options...
```

Like I said, I removed `connectWithNoPrimary` and it worked.

**Comment by christkv** [comment] 2017-03-06 17:08
We think we have a fix for this scenario here https://github.com/christkv/mongodb-core/commit/720251fa966b11902ea3fe369d8296cbf39d403a although there is no reason to ever use connectWithNoPrimary unless you know you can live with secondary only queries.

**Comment by gfzabarino** [comment] 2017-03-06 17:14
This is the line that sets to `primary` the read preference by default: https://github.com/christkv/mongodb-core/blob/2.0/lib/topologies/replset_state.js#L609

Maybe you could pass a default options to `getServer` in here:

https://github.com/christkv/mongodb-core/blob/2.0/lib/cursor.js#L546

to allow secondaries under the given scenario.. But you're right, there seems to be some conflict between the db configuration and the cursor's options which shouldn't be there in the first place.

Feel free to close this issue, thanks for the quick response.

**Comment by christkv** [comment] 2017-03-06 17:22
The default readPreference is primary, operations should fail if you have not specifically said you can live with a secondary read and the possible tradeoff in consistency. 

If you look at the cursor code the operation will get buffered until there is a primary available then gets re-executed.

However the bug you were seeing might be related to the https://github.com/christkv/mongodb-core/commit/720251fa966b11902ea3fe369d8296cbf39d403a commit fix where the bug in the ismaster fetching caused operations to fail.

**Comment by gfzabarino** [comment] 2017-03-06 17:25
Sure but, about that failure, should it be a Type Error? I don't think https://github.com/christkv/mongodb-core/commit/720251fa966b11902ea3fe369d8296cbf39d403a would fix that (but to be honest, I didn't try it).

```
TypeError: Cannot read property 'command' of undefined
    at nextFunction (xxx/node_modules/mongodb-core/lib/cursor.js:568:51)
```

**Comment by christkv** [comment] 2017-03-06 17:28
yes that error is caused by https://github.com/christkv/mongodb-core/commit/720251fa966b11902ea3fe369d8296cbf39d403a due to the driver not being able to identify the wire protocol handler to use and thus you are getting that error.

Also it's not

j:'majority' but w:'majority' and you should also set wtimeout to ensure you writes don't hang for ever if you do not have a majority of replicaset members up and running.

Also be aware that majority write concern comes with a write performance impact as you have to wait until a majority of replicaset members acknowledge the write.

**Comment by gfzabarino** [comment] 2017-03-06 17:29
You're right about everything you wrote, thanks for that!

**Comment by christkv** [comment] 2017-03-06 17:30
np

**Closed by christkv** 2017-03-06 17:30 UTC
