### ISSUE TITLE
Sometimes replica set master reference doesn't change after network loss

### ISSUE THREAD

**Issue by jakesjews** [christkv/mongodb-core#148] opened 2016-10-31 22:28 UTC
Making a new issue since I can't reopen https://github.com/christkv/mongodb-core/issues/145. 

This is with version 2.0.12, mongodb 3.2.10 and ubuntu 14.04.

This issue may be related to #144 and the setup is pretty similar.

You will need either 3 VMs or 3 physical servers to replicate this issue. This does not happen if the service is only stopped while the server is on the network or if the script is running before the node leaves the network.

Steps to replicate
- Spin up a replica set on three linux servers
- Start this script on all three nodes
  
  ```
  var ReplSet = require('mongodb-core').ReplSet;
  var replSet = new ReplSet([
    { host: server1Ip, port: 27017 },
    { host: server2Ip, port: 27017 },
    { host: server3ip, port: 27017 }
  ]);
  
  replSet.on('connect', function(_server) {
    setInterval(function() {
      _server.command('system.$cmd', { ping: 1 }, function(err, result) {
        if (err) {
          console.error(err);
        } else {
          console.log(result.result);
        }
      });
    }, 1000);
  });

  replSet.connect()
  ```
- Disconnect the network from the master server either by pulling out a network cable or using ifdown on the interface.
- Most of the time (but not always) one of the scripts running on one of the nodes still connected to the network will get stuck in a loop throwing errors trying to connect to the old master.
- Here is a [video showing the issue](http://recordit.co/GXpTLCCakd)

**Comment by jakesjews** [comment] 2016-11-16 19:56
@christkv it looks like this is fixed with the latest commits on master! Any chance this is going to be released soon?

**Comment by christkv** [comment] 2016-11-18 11:43
It will be released no later than the 29th of this month as we have to have final 3.4 drivers ready.

**Comment by jakesjews** [comment] 2016-11-18 19:53
@christkv so it turns out I made a mistake. When I was testing out the changes I used a package.json entry `"mongodb-core": "christkv/mongodb-core"` which was pulling from the master branch instead of 2.0. It looks like the issue is still happening.

**Comment by christkv** [comment] 2016-11-22 11:21
Cannot reproduce this using virtual machine using the latest 2.0 branch and ubuntu 14.04. One thing I want to point out however. Why are you running the app scripts on the mongod instances themselves ? This really is a weird use case. Most people run app server on separate instances from their mongodb servers and this is the recommended way to deploy mongodb.

**Comment by jakesjews** [comment] 2016-11-22 13:59
Would it be possible to screen share or something it is extremely easy for me to reproduce it. It is important to note the issue doesn't happen if you gracefully shut down the mongo service you need to actually disconnect the network.

The reason we are running it like that is that we run on assembly lines where there is no internet so we only have three servers for a replica set. The server that the app code is running on should have no impact on how it connects over TCP if I understand correctly?

**Comment by christkv** [comment] 2016-11-22 14:37
I might be able to tomorrow, I'm based in Spain so no later than 4pm CET is best for me as I have meetings after that. I tried to reproducing it with 3 different vm's running and the scripts running on each of the servers vms and disconnected the networking on a secondary as per the video and then waited for a couple of minutes but everything kept working.

Now one questions I have is are all the ips in rs.config() resolvable by all the scripts that are running ?

Putting the scripts on a different instance than the server has a profound impact because they can still view parts of the set even when one server instance gets cut off due to a disabled networking interface however I'm not sure it would change the outcome of what you are seeing in according to the video.

**Comment by jakesjews** [comment] 2016-11-22 14:46
Thanks for the reply sorry about pushing so hard on this but we are getting near the end of a project and the assembly line guys want to prove out the failover of the system since the line needs to keep running in the event of a network failure. I'm cool for any time between 9am-12PM EST. Hopefully Ill be able to get a PR by the end of today instead.

The ips are resolvable from each of the three nodes. It looks like whats happening is that the callback on https://github.com/christkv/mongodb-core/blob/2.0/lib/topologies/replset.js#L520 is not firing for the disconnected server even after the timeout. I'm currently digging into the error handler to see why the callback isn't sending an error. Another thing I was wondering about is if https://github.com/christkv/mongodb-core/commit/5b996789fa052a22ddbd680565befa2a11281fd9#diff-dc27eebcc66ed957fe1f8d58c5387d0dL531 is prevent heartbeat fails from causing the master reference to change.

**Comment by christkv** [comment] 2016-11-22 15:10
9 am EST sounds good, let me know your email ( you can email me at christkv at mongodb com) and I'll set up an appear in video call. Still not sure why I cannot reproduce it. I ended up trying both vm ware and parallels workstation after giving up on the broken vagrant install for osx.

**Comment by christkv** [comment] 2016-11-23 20:26
@jakesjews I managed to fix. The bug was simple the fix a little more complicated to figure out.

**Comment by jakesjews** [comment] 2016-11-23 20:27
@christkv awesome news thanks a bunch for the help!

**Comment by christkv** [comment] 2016-11-23 20:30
@jakesjews don't thank me yet :). I would like confirmation from you first.

**Comment by jakesjews** [comment] 2016-11-23 20:30
Heh firing up the VMs right now

**Comment by jakesjews** [comment] 2016-11-23 20:36
@christkv I cut off the master 5 times and it seems to recover quickly now. So it seems like its working well.

**Comment by christkv** [comment] 2016-11-23 20:37
Awesome I'm going to close the ticket then 👍 , if you run into anything else please open a new ticket.

**Closed by christkv** 2016-11-23 20:37 UTC
