### ISSUE TITLE
reconnect event fails to fire sometimes

### ISSUE THREAD

**Issue by catdad** [christkv/mongodb-core#142] opened 2016-10-07 16:06 UTC
mongodb version: 2.2.10
mongodb-core version: 2.0.12
node version: 4.4.2 (probably irrelevant)

Testing on Windows 10 and Ubuntu 16.04.

When setup with a pool connection, the reconnect event fails to fire sometimes. I say sometimes, but in my tests, it actualy always fires on Ubuntu and never fires on Windows. After debugging the code, it looks like it _should be_ sometimes though. This leads to all sorts of issues. Most notably, if there is an operation, such as an insert, when the DB is not connected, that operation gets stored in the disconnect store, which is flushed on the reconnect event. No reconnect event, no flush, and you have a bunch of stuck code waiting for its callback to be called. However, on both Windows and Ubuntu, the driver definitely reconnects, as I am able to interact with the database after killing the mongod binary and bringing it back up. I have tests for all of this, so it is very reproducible -- if needed, I will extract some of them from my app and provide them here.

I debugged this quite a bit this morning. The issue appears to be [here, in the reconnect logic](https://github.com/christkv/mongodb-core/blob/5b996789fa052a22ddbd680565befa2a11281fd9/lib/connection/pool.js#L276-L279).

Let me explain. The reconnect event only fires [after a connection and after authentication](https://github.com/christkv/mongodb-core/blob/5b996789fa052a22ddbd680565befa2a11281fd9/lib/connection/pool.js#L335). However, before attempting to reconnect, it [checks whether it is already connected](https://github.com/christkv/mongodb-core/blob/5b996789fa052a22ddbd680565befa2a11281fd9/lib/connection/pool.js#L276-L279) and skips doing anything. In the `isConnected` check, there is a state where [the connection exists but it is not authenticated yet](https://github.com/christkv/mongodb-core/blob/5b996789fa052a22ddbd680565befa2a11281fd9/lib/connection/pool.js#L526-L528), which is treated as connected.

Now, I am not totally sure where the actual reconnect happens, but in my tests so far, I am seeing that on Windows, it attempts to reconnect once or twice, fails with an ECONNREFUSED, and on the next try, it hits this `isConnected` check, where it returns. The reconnect event never fires, so it must not be this function which is doing the actual reconnect. Either way, if when doing that check, I also fire the reconnect event, the rest of the app works fine. The disconnect store is flushed and everything executes correctly as it does on Ubuntu. This may not be the correct place in the code though, as it might be better to fire the reconnect event in the place where the connection actually gets reconnected. Theoretically, this is a timing issue and not a Windows vs. Linux issue, but in my tests, it is way more apparent on Windows.

**Comment by catdad** [comment] 2016-10-07 17:35
Okay, never mind. It is not a connected but not-yet authenticated connection. It actually has a connection in one of the arrays it checks. But never the less, the connection is reconnected without actually firing the reconnect event.

**Comment by catdad** [comment] 2016-10-10 20:37
Okay, I found the actual issue. Sorry for the long misleading paragraph above. This long paragraph below is the actual issue:

In my test, I write a steady stream of data to the database. In the middle of that stream, I kill mongod and start it back up, making sure to write some data before, during, and after the outage. However (and this is key), I don't control how fast after th outage I write more data.

I did some more prodding to see when and how new connections are connected, and got this stack trace:

```
Trace
  at Connection.connect (C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:376:11)
  at _createConnection (C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:1011:14)
  at C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:1056:11
  at waitForAuth (C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:1034:39)
  at C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:1042:5
  at Pool.write (C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:911:17)
  at null._onTimeout (C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:208:17)
  at Timer.listOnTimeout (timers.js:92:15)
```

The important parts are in `pool.js`. Tracing this in mongodb-core v2.0.12, I found that this is a result of doing a database [write while there are no resent connections](https://github.com/christkv/mongodb-core/blob/5b996789fa052a22ddbd680565befa2a11281fd9/lib/connection/pool.js#L1046-L1055). In this case, it will just try to make a new connection, and it happens to succeed at some point. If this happens in between reconnect retries, the reconnect function will check `isConnected()` and get true, therefore skipping firing the reconnect event.

**Comment by christkv** [comment] 2016-10-26 10:43
please reopen if still happening with 2.2.11

**Comment by catdad** [comment] 2016-10-26 12:42
I'm not actually allowed to re-open... so I will just comment.

I ran the tests for my service this morning with mongodb 2.2.11 and mongodb-core 2.0.13. The issue is happening far less now (it used to be reproduces almost every time). Now, I have to do quite a few retries to get a repro, but it did happen a couple of times. I took a look at the compare pages for mongodb and mongodb-core and don't actually see anything that addresses this problem.

Also, I got this new error as well... which I probably need to file a new bug for...

```
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at Socket.Writable.write (_stream_writable.js:212:5)
    at Socket.write (net.js:626:40)
    at Connection.write (C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:500:53)
    at C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:1138:26
    at waitForAuth (C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:1083:39)
    at C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:1091:5
    at C:\Workspace\Gitlab\text-service\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:958:21
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

**Comment by christkv** [comment] 2016-10-26 13:01
if you open a new issue I will need a sample script that reproduces the issue as well as any other steps you are taking so I can reproduce it locally.

**Comment by christkv** [comment] 2016-10-27 13:42
I have a theory about how to fix this. after the latest refactoring the only connections that should define if isConnected is possible should be availableConnections. This should avoid auth connections ever make the pool available.

**Comment by bompus** [comment] 2016-11-09 16:46
@christkv - It looks like this will make it into 2.0.14 - couple of questions..

1) any chance this also addresses #148 ?
2) any idea when 2.0.14 / 2.2.12 will be released?

**Comment by christkv** [comment] 2016-11-09 16:49
1) it's possible but I've not been able to repo #148 successfully so cannot guarantee.
2) I need to get some other things of my plate first but I'm hoping to get a release out no later than end of month but I have some tickets that need to be closed for MongoDB 3.4 support first due to spec changes on new features.

**Comment by jakesjews** [comment] 2016-11-11 01:56
@christkv If you need help reproducing the issue I can recreate it pretty easily with VMs. The company I work for is planning on shipping a product fairly soon and we need to get failover working before that so I am available to screen share if it would help.

**Comment by christkv** [comment] 2016-11-11 11:03
Can you suggest a setup that will reproduce it and the steps to make it happen. I have vms available but just need step by step instructions.

**Comment by catdad** [comment] 2016-11-11 13:11
Sorry, I meant to port my tests into the mongo unit test suite, but never got time for it. I'll try to summarize here. My application code looks a little something like this:

```javascript
var through = require('through2');

// I expect this to stay connected (or reconnect) for the entire lifetime of the app
var mongo = getMongoConnectionSomehow();

function saveTheData() {
    // optimize saves by gathering the data read on the stream into an array,
    // so that if Mongo takes longer to save than the rate of reads,
    // we save all the data that has been read since the last save all at once
    return throttleReadsSoThatWeCollectWrittenDataBeforeEachMongoFlush()
        .pipe(through.obj(function onData(arrayOfData, enc, cb) {
            var that = this;
            
            mongo.insertMany(arrayOfData, function(err) {
                if (err) {
                    return cb(err);
                }
                
                arrayOfData.forEach(function(data) {
                    that.push(data);
                });
                
                cb();
            });
        }));
}

// get an object stream of data... my data is
// around 3300 characters of JSON, as a parsed object
getStreamOfIndividualDataItems()
    .pipe(saveData())
    // do something with the data that is not
    // realy relevant to this test
    .on('data', doSomething);
```

Then, in my tests, I have the following scenarios (**all using async to make sure each step finishes before moving to the next step**):

`writeArrayOfData`: a helper that writes each data point, waiting about 5ms between writes
`connectMongo`: uses spawn to start mongod, establish new driver connection before calling callback
`disconnectMongo`: uses `mongo.runCommand({ shutdown: 1 }` to kill the running process (since on Windows, we can't just SIGINT the spawned process)

_Note: all pseudocode_

```javascript

// disconnect once toward the beginning of the data stream

connectMongo()
writeArrayOfData(4 element array)
disconnectMongo()
connectMongo()
writeArayOfData(16 element array)
```

```javascript

// disconnect once toward the end of the data stream

connectMongo()
writeArrayOfData(19 element array)
disconnectMongo()
connectMongo()
writeArayOfData(1 element array)
```

```javascript

// disconnect once between writing each piece of data

connectMongo();

async.each([20 data elements], function(data, next) {
    disconnectMongo();
    writeAtayOfData([data]);
    connectMongo();
    next();
});
```

In the version that I reported the bug with, at least one test would fail each time on Windows. With the version that you mentioned in the update, it's much more stable -- I have to run the tests upwards of 20 times before it fails. Hope this helps. Let me know if you need more info.

**Comment by jakesjews** [comment] 2016-11-11 14:24
@christkv I had pretty detailed instructions in the issue I filed. Did it not show the same issue?

**Comment by christkv** [comment] 2016-11-24 09:54
@catdad feel free to test the latest 2.0 branch as there was some important bug fixes that went in to fix an issue @jakesjews identified and that could well be responsible for the behavior you are seeing.

**Comment by christkv** [comment] 2017-01-03 13:53
2.2.18 should have addressed these issues

**Closed by christkv** 2017-01-03 13:53 UTC
