### ISSUE TITLE
Connection issues 

### ISSUE THREAD

**Issue by AlexDenisov** [christkv/mongodb-core#161] opened 2017-02-10 10:48 UTC
Hi there,

Just wanted to let you know: after upgrading from 2.0.14 to 2.1.7 we started seeing errors as follows:
```
MongoError: connection 2427 to <host:port> timed out
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:186:20)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Downgrading back to 2.0.14 solved the problem*.

Unfortunately, I could not bisect exact version where the problem appears since it takes 6-20 hours to make sure that problem is or is not happening anymore.

Some stats: we have ~30k requests per day, for two weeks we saw ~600 occurrences of this error.
Please, let me know if I can help you with the investigation.

* at least we can't see timeout errors anymore.

**Comment by christkv** [comment] 2017-02-13 07:57
You should move to the 2.2.22 or higher driver not to the 2.1.x series. 2.2.23 will be out today with some minor improvements so hold off until tomorrow.

**Comment by amc2014** [comment] 2017-02-13 09:14
Hello,

I'm having random timeouts problem too with 2.2.22 (mongoose 4.8.1 -> mongodb 2.2.22 -> mongodb-core 2.1.7). Running aggregation on large collection (70 million records) times out after random periods of time, typically between 10 and 30 seconds. Here is the stack trace:
MongoError: connection 2 to /tmp/mongodb-27017.sock:27017 timed out 
    at /home/test/src/app/test_modules/lib/background_jobs/test.js:133:27
    at /home/test/src/node_modules/async/lib/async.js:251:17
    at /home/test/src/node_modules/async/lib/async.js:148:21
    at /home/test/src/node_modules/async/lib/async.js:248:21
    at /home/test/src/node_modules/async/lib/async.js:612:34
    at /home/test/src/node_modules/mongoose/lib/aggregate.js:658:15
    at handleCallback (/home/test/src/node_modules/mongodb/lib/utils.js:95:56)
    at /home/test/src/node_modules/mongodb/lib/collection.js:2689:7
    at handleCallback (/home/test/src/node_modules/mongodb/lib/utils.js:95:56)
    at Object.cb (/home/test/src/node_modules/mongodb/lib/db.js:311:20)
    at null.<anonymous> (/home/test/src/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:243:32)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/home/test/src/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:185:10)
Timeout (socketTimeoutMS) is set to 0, connection is established via unix socket, code is running in docker container (with mongo db stored in mounted docker volume). Both docker and the host are running debian. I would appreciate your could help resolving this issue. A quick web search shows a lot of people affected by this problem.

Thank you!
Andrey Mikhalchuk

**Comment by christkv** [comment] 2017-02-13 09:19
There is a fix that improves scheduling of long running aggregations coming in 2.2.23. Other than that 0 is not some sort of magic option, all it does it delegate the timeout setting to the OS level or in your case docker container. I would suggest setting socket timeout to 2-3x the longest running query time and also adjust the os/docker container default socket timeout.

**Comment by amc2014** [comment] 2017-02-13 09:24
Christian, appreciate your lightning fast response!
I doubt the problem is in the OS/docker since it occurs randomly. Also web search shows reports from people running into the same issue without docker, unix sockets etc. So I'll be waiting for mongoos to eventually upgrade to 2.2.23 which was released 22 minutes ago.
Really appreciate your hard work.

Sincerely,

**Comment by dbellavista** [comment] 2017-02-13 16:27
Hi @christkv ,
I'm having difficulties setting a socket timeout. In our production system it's much more likely to have a stable connection running a very long query (15min +).
During the deploy I'm applying this patch to get it work:

```
diff -Naur node_modules/mongodb-core/lib/topologies/server.js ../../node_modules/mongodb-core/lib/topologies/server.js
--- node_modules/mongodb-core/lib/topologies/server.js	2016-12-08 22:48:44.000000000 +0100
+++ ../../node_modules/mongodb-core/lib/topologies/server.js	2016-12-23 17:49:01.000000000 +0100
@@ -215,7 +215,7 @@
     var start = new Date().getTime();
     // Execute the ismaster query
     self.s.pool.write(query, {
-      socketTimeout: self.s.options.connectionTimeout || 2000,
+      socketTimeout: (typeof self.s.options.connectionTimeout !== 'number') ? 2000 : self.s.options.connectionTimeout,
     }, function(err, result) {
       // Set initial lastIsMasterMS
       self.lastIsMasterMS = new Date().getTime() - start;
```

This allows me to set `connectionTimeout` to `0`, which by convention means no timeout (https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback).

I think this behaviour should be allowed..

**Comment by christkv** [comment] 2017-02-13 16:35
Just set up a PR and I'll have a look at it. However don't be fooled 0 does not mean no timeout, it just defers to the os which will timeout the connection at some point. I think linux default is mostly 30 minutes.

**Comment by dbellavista** [comment] 2017-02-13 16:36
Ah thanks, I didn't know it. Ok, I'll setup a PR :)

**Comment by christkv** [comment] 2017-03-17 10:39
merged PR

**Closed by christkv** 2017-03-17 10:39 UTC

**Comment by iranfard** [comment] 2017-12-13 22:38
In my case, the problem was file security on the new server and mongdb npm module files, so I had to use "chown" command to own all files and then run "npm install", after that MongoDB client worked properly.
